// Copyright 2023 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

// #include "rgb/anim/startup_swirl_anim.h" // Requires matrix positions to work
// #include "rgb/anim/my_party_rocks.h" // seizure warning
// #include "rgb/anim/cool_diagonal.h"         // neaat
// #include "rgb/anim/random_breath_rainbow.h" // rgb vomit!
// #include "rgb/anim/custom_gradient.h" // too custom
// #include "rgb/anim/raindrops.h"
// #include "rgb/anim/candy.h"
// #include "rgb/anim/alpha_mod_homerow.h"
// #include "rgb/anim/alpha_mod_homerow_cycle.h"
// #include "rgb/anim/tetris_falling.h"
// #include "rgb/anim/tetris_falling_horizontal.h"
// #include "rgb/anim/solid_reactive_custom.h"
// #include "rgb/anim/starry_night.h"
