// Copyright 2023 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#undef OLED_DISPLAY_128X64
#define OLED_DISPLAY_128X128
#define OLED_BRIGHTNESS 200

#define CHARYBDIS_MINIMUM_DEFAULT_DPI     3000
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 600
#define CHARYBDIS_MINIMUM_SNIPING_DPI     400
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 200

#define BOOTMAGIC_EEPROM_ROW          1
#define BOOTMAGIC_EEPROM_COLUMN       0
#define BOOTMAGIC_EEPROM_ROW_RIGHT    7
#define BOOTMAGIC_EEPROM_COLUMN_RIGHT 5

#undef DRV2605L_GREETING
#define DRV2605L_GREETING DRV2605L_EFFECT_750_MS_ALERT_100
#undef DRV2605L_DEFAULT_MODE
#define DRV2605L_DEFAULT_MODE DRV2605L_EFFECT_BUZZ_4_40

#define PMW33XX_LIFTOFF_DISTANCE 0b1111

#define LAYER_MAP_REMAPPING
#define LAYER_MAP_COLS 17
#define LAYER_MAP_ROWS 8

#if defined(KEYBOARD_handwired_tractyl_manuform_5x6_right_f405)
#    ifdef USE_USB_OTG_HS_PORT
#        define USB_ENDPOINTS_ARE_REORDERABLE
#    endif
#    define RGBLIGHT_LIMIT_VAL 255
#    undef RGB_MATRIX_MAXIMUM_BRIGHTNESS
#    define RGB_MATRIX_MAXIMUM_BRIGHTNESS    255
#    define LUMINO_HIGH_BRIGHTNESS           0.78431372549
#    define LUMINO_LOW_BRIGHTNESS            0.392156862745
#    define MATRIX_OUTPUT_SELECT_DELAY_NOP   20
#    define MATRIX_OUTPUT_UNSELECT_DELAY_NOP 25
#    undef SERIAL_USART_SPEED
#    define SERIAL_USART_SPEED (1.5 * 1024 * 1024)
#    undef PMW33XX_LIFTOFF_DISTANCE
#    define PMW33XX_LIFTOFF_DISTANCE 0b0011
#elif defined(KEYBOARD_handwired_tractyl_manuform_5x6_right_f411)
#    undef SPLIT_HAND_PIN
#    define SPLIT_HAND_PIN A9
#    define DISPLAY_CS_PIN B10
#    define DISPLAY_DC_PIN B2
#endif
#ifdef WEAR_LEVELING_SPI_FLASH
#    undef WEAR_LEVELING_LOGICAL_SIZE
#    undef WEAR_LEVELING_BACKING_SIZE
#    define WEAR_LEVELING_SIZE_KB            16
#    define WEAR_LEVELING_BACKING_MULTIPLIER 4
#    define WEAR_LEVELING_LOGICAL_SIZE       (WEAR_LEVELING_SIZE_KB * 1024)
#    define WEAR_LEVELING_BACKING_SIZE       (WEAR_LEVELING_SIZE_KB * 1024 * WEAR_LEVELING_BACKING_MULTIPLIER)
#else
#    ifndef WEAR_LEVELING_BACKING_SIZE
#        define WEAR_LEVELING_BACKING_SIZE (0x4000)
#    endif
#endif

#if !defined(CUSTOM_QUANTUM_PAINTER_ILI9488) && !defined(QUANTUM_PAINTER_DISPLAY_TIMEOUT)
#    define QUANTUM_PAINTER_DISPLAY_TIMEOUT 600000
#endif
#define SPLIT_USB_TIMEOUT      500
#define SPLIT_WATCHDOG_TIMEOUT 700
