// Copyright 2024 Christopher Courtney, aka Drashna Jael're  (@drashna) <drashna@live.com>
// SPDX-License-Identifier: GPL-3.0-or-later

#pragma once

#ifndef QUANTUM_PAINTER_DISPLAY_TIMEOUT
#    define QUANTUM_PAINTER_DISPLAY_TIMEOUT 3600000
#endif
#ifndef QUANTUM_PAINTER_TASK_THROTTLE
// 33ms gets roughtly 30 frames per second
#    define QUANTUM_PAINTER_TASK_THROTTLE 33
#endif // QUANTUM_PAINTER_TASK_THROTTLE
#ifndef QUANTUM_PAINTER_NUM_IMAGES
#    define QUANTUM_PAINTER_NUM_IMAGES 22
#endif // QUANTUM_PAINTER_NUM_IMAGES
#ifndef QUANTUM_PAINTER_SUPPORTS_256_PALETTE
#    define QUANTUM_PAINTER_SUPPORTS_256_PALETTE TRUE
#endif // QUANTUM_PAINTER_SUPPORTS_256_PALETTE
#ifndef QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS
#    define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
#endif // QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS
#ifndef QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE
#    define QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE 2048
#endif // QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE
#ifndef SURFACE_NUM_DEVICES
#    define SURFACE_NUM_DEVICES 2
#endif // SURFACE_NUM_DEVICES
